# Generated by Django 2.1.5 on 2019-04-08 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('createTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('content', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('image', models.CharField(max_length=255, null=True)),
                ('finished_time', models.DateField(null=True)),
                ('createTime', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=16, null=True)),
                ('name', models.TextField(max_length=20, null=True)),
                ('contact', models.TextField(max_length=100, null=True)),
                ('is_bind', models.BooleanField(default=False)),
                ('createTime', models.DateField()),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='buy_user',
            field=models.ForeignKey(db_column='buy_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_buy_user', to='flea.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='publisher',
            field=models.ForeignKey(db_column='publisher', on_delete=django.db.models.deletion.CASCADE, related_name='good_publisher', to='flea.User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='goods',
            field=models.ForeignKey(db_column='goods', on_delete=django.db.models.deletion.CASCADE, related_name='user_collection', to='flea.Goods'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='flea.User'),
        ),
    ]
